version: '2'

services:
    user-input-dc:
        extends:
            file: user_input_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - user-input-dc.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-user-input-dc
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "reasons-db"
    reasons-db:
        extends:
            file: reasons_sds/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - reasons-db.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-reasons-db
        env_file:
            - django_secret_key
        restart: unless-stopped
        
    timeseries-db:
        extends:
            file: timeseries_sds/app.yml
            service: db
        networks:
            internal:
                aliases:
                    - timeseries-db.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-timeseries-db
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    timeseries-db-input:
        extends:
            file: timeseries_sds/app.yml
            service: telegraf
        networks:
            internal:
                aliases:
                    - timeseries-input.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - mqtt.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-mqtt-broker
        restart: unless-stopped
    dashboard:
        extends:
            file: dashboard_ui/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-dashboard-ui
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
networks:
    internal:
        name: shoestring-internal
